const PDFDocument = require('pdfkit');

const generatePDF = (report, res) => {
    const doc = new PDFDocument({
        margin: 50,
        size: 'A4'
    });

    res.setHeader(
        'Content-Disposition',
        `attachment; filename="${report.title}.pdf"`
    );

    res.setHeader(
        'Content-Type',
        'application/pdf'
    );

    doc.pipe(res);

    doc.fontSize(22)
        .text(report.title, {
            align: 'center'
        });

    doc.moveDown();

    doc.fontSize(12);

    doc.text(`Report Type: ${report.reportType}`);
    doc.text(`Generated: ${new Date(report.generatedAt).toLocaleString()}`);

    if (report.generatedBy?.fullName) {
        doc.text(`Generated By: ${report.generatedBy.fullName}`);
    }

    doc.moveDown();

    doc.fontSize(16).text("Summary");

    doc.moveDown(0.5);

    if (report.summary) {

        Object.entries(report.summary).forEach(([key, value]) => {

            doc.text(`${key}: ${value}`);

        });

    }

    doc.moveDown();

    doc.fontSize(16).text("Data");

    doc.moveDown(0.5);

    doc.fontSize(10);

    doc.text(
        JSON.stringify(report.data, null, 2)
    );

    doc.end();
};

module.exports = generatePDF;