import React from 'react';
import { reportsAPI } from '../../api/reports';

const ReportViewer = ({ report, data }) => {
  if (!data) {
    return (
      <div className="text-center py-8 text-gray-500">
        No report data available.
      </div>
    );
  }

  const formatDate = (date) => {
    if (!date) return '-';
    return new Date(date).toLocaleDateString();
  };

  const reportType = report?.reportType || '';

  return (
    <div className="bg-white rounded-lg p-6">

      {/* Header */}
      <div className="text-center border-b-2 border-emerald-600 pb-4 mb-6">
        <h1 className="text-3xl font-bold">
          MUSHROOM FARM INFORMATION MANAGEMENT SYSTEM
        </h1>

        <h2 className="text-xl text-emerald-600 mt-2 font-semibold">
          {reportType}
        </h2>

        <div className="grid grid-cols-2 gap-2 mt-5 text-sm">
          <p>
            <strong>Generated By:</strong>{" "}
            {report?.generatedBy?.fullName || 'Administrator'}
          </p>

          <p>
            <strong>Date:</strong>{" "}
            {formatDate(report?.generatedAt)}
          </p>
          <p>
            <strong>Period:</strong>{" "}
            {data.summary?.dateRange?.startDate || "-"}
            {" - "}
            {data.summary?.dataRange?.endDate || "-"}
          </p>
          <p>
            <strong>Status:</strong>
            Completed
          </p>
        </div>
      </div>

      <div className="flex justify-end gap-3 mb-6">
            <button
                onClick={() => window.print()}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
                >
                <i className="fas fa-print mr-2"></i>
                Print
            </button>

           <button
            onClick={async () => {
                try {
                const response = await reportsAPI.download(report._id);

                const blob = new Blob([response.data], {
                    type: "application/pdf",
                });

                const url = window.URL.createObjectURL(blob);

                const link = document.createElement("a");
                link.href = url;
                link.download = `${report?.reportType || 'Report'} - ${report?.reportNumber || 'Unknown'}.pdf`;

                document.body.appendChild(link);
                link.click();

                link.remove();
                window.URL.revokeObjectURL(url);
                } catch (error) {
                console.error(error);
                alert("Failed to download report.");
                }
            }}
            className="px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition"
            >
            <i className="fas fa-download mr-2"></i>
            Download PDF
            </button>
        </div>

      {/* Summary */}
        {data.summary && (
            <>
                <h3 className="text-lg font-semibold text-gray-800 mb-4">
                  Report Summary
                </h3>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
                {Object.entries(data.summary)
                    .filter(([_, value]) => typeof value !== "object")
                    .map(([key, value]) => (
                    <div
                        key={key}
                        className="bg-white border rounded-xl shadow-sm p-5 hover:shadow-md transition"
                    >
                        <p className="text-xs uppercase tracking-wide text-gray-500">
                        {key.replace(/([A-Z])/g, " $1")}
                        </p>

                        <h2 className="text-2xl font-bold text-emerald-600 mt-2">
                        {typeof value === "number"
                            ? value.toLocaleString()
                            : value}
                        </h2>
                    </div>
                    ))}
                </div>
            </>
        )}

      {/* Production Report Table */}
      {reportType === 'Production Report' && data.batches && (
        <>
          <h3 className="text-lg font-semibold mb-4">
            Production Details
          </h3>

          <div className="overflow-x-auto">
            <table className="w-full border border-gray-200">
              <thead className="bg-emerald-600 text-white">
                <tr>
                  <th className="p-3 text-left">Batch No.</th>
                  <th className="p-3 text-left">Mushroom</th>
                  <th className="p-3 text-left">Harvest</th>
                  <th className="p-3 text-left">Loss</th>
                  <th className="p-3 text-left">Status</th>
                </tr>
              </thead>

              <tbody>
                {data.batches.map((batch, index) => (
                  <tr
                    key={index}
                    className="border-t hover:bg-gray-50"
                  >
                    <td className="p-3">{batch.batchNumber}</td>
                    <td className="p-3">{batch.mushroomType}</td>
                    <td className="p-3">{batch.totalHarvest} Kg</td>
                    <td className="p-3">{batch.productionLoss} Kg</td>
                    <td className="p-3">{batch.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      {/* Inventory Report Table */}
      {reportType === 'Inventory Report' && data.items && (
        <>
          <h3 className="text-lg font-semibold mb-4">
            Inventory Items
          </h3>

          <div className="overflow-x-auto">
            <table className="w-full border">
              <thead className="bg-emerald-600 text-white">
                <tr>
                  <th className="p-3">Item Code</th>
                  <th className="p-3">Item Name</th>
                  <th className="p-3">Category</th>
                  <th className="p-3">Quantity</th>
                  <th className="p-3">Stock Status</th>
                </tr>
              </thead>

              <tbody>
                {data.items.map((item, index) => (
                  <tr
                    key={index}
                    className="border-t"
                  >
                    <td className="p-3">{item.itemCode}</td>
                    <td className="p-3">{item.itemName}</td>
                    <td className="p-3">{item.category}</td>
                    <td className="p-3">{item.quantity}</td>
                    <td className="p-3">{item.stockStatus}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      {reportType === "Sales Report" && data.sales && (
            <>
                <h3 className="text-lg font-semibold mb-4">
                  Sales
                </h3>

                <div className="overflow-x-auto">
                <table className="w-full border">
                    <thead className="bg-emerald-600 text-white">
                    <tr>
                        <th className="p-3">Sale No</th>
                        <th className="p-3">Customer</th>
                        <th className="p-3">Amount</th>
                        <th className="p-3">Paid</th>
                        <th className="p-3">Status</th>
                    </tr>
                    </thead>

                    <tbody>
                    {data.sales.map((sale, index) => (
                        <tr key={index} className="border-t">
                        <td className="p-3">{sale.saleNumber}</td>
                        <td className="p-3">{sale.customerName}</td>
                        <td className="p-3">RWF {sale.totalAmount}</td>
                        <td className="p-3">RWF {sale.amountPaid}</td>
                        <td className="p-3">{sale.paymentStatus}</td>
                        </tr>
                    ))}
                    </tbody>
                </table>
                </div>
            </>
        )}

        {reportType === "Customer Report" && data.customers && (
            <>
                <h3 className="text-lg font-semibold mb-4">
                  Customer Details
                </h3>

                <div className="overflow-x-auto">
                <table className="w-full border">
                    <thead className="bg-emerald-600 text-white">
                        <tr>
                            <th className="p-3">Customer Code</th>
                            <th className="p-3">Full Name</th>
                            <th className="p-3">Phone</th>
                            <th className="p-3">Customer Type</th>
                            <th className="p-3">Orders</th>
                            <th className="p-3">Total Spent</th>
                            <th className="p-3">Status</th>
                        </tr>
                    </thead>

                    <tbody>
                    {data.customers.map((customer, index) => (
                        <tr key={index} className="border-t hover:bg-gray-50">
                        <td className="p-3">{customer.customerCode}</td>
                        <td className="p-3">{customer.fullName}</td>
                        <td className="p-3">{customer.phoneNumber}</td>
                        <td className="p-3">{customer.customerType}</td>
                        <td className="p-3">{customer.totalOrders}</td>
                        <td className="p-3">RWF {customer.totalSpent}</td>
                        <td className="p-3">
                            {customer.isActive ? "Active" : "Inactive"}
                        </td>
                        </tr>
                    ))}
                    </tbody>
                </table>
                </div>
            </>
        )}

        {reportType === "Order Report" && data.orders && (
            <>
                <h3 className="text-lg font-semibold mb-4">
                  Order Details
                </h3>

                <div className="overflow-x-auto">
                <table className="w-full border">
                    <thead className="bg-emerald-600 text-white">
                    <tr>
                        <th className="p-3">Order No.</th>
                        <th className="p-3">Customer</th>
                        <th className="p-3">Phone</th>
                        <th className="p-3">Items</th>
                        <th className="p-3">Amount</th>
                        <th className="p-3">Status</th>
                        <th className="p-3">Payment</th>
                    </tr>
                    </thead>

                    <tbody>
                    {data.orders.map((order, index) => (
                        <tr key={index} className="border-t hover:bg-gray-50">
                        <td className="p-3">{order.orderNumber}</td>
                        <td className="p-3">{order.customerName}</td>
                        <td className="p-3">{order.customerPhone}</td>
                        <td className="p-3">{order.totalItems}</td>
                        <td className="p-3">RWF {order.totalAmount}</td>
                        <td className="p-3">{order.status}</td>
                        <td className="p-3">{order.paymentStatus}</td>
                        </tr>
                    ))}
                    </tbody>
                </table>
                </div>
            </>
        )}

        {reportType === "Stock Movement Report" && data.movements && (
            <>
                <h3 className="text-lg font-semibold mb-4">
                  Stock Movement Details
                </h3>

                <div className="overflow-x-auto">
                <table className="w-full border">
                    <thead className="bg-emerald-600 text-white">
                        <tr>
                            <th className="p-3">Item Code</th>
                            <th className="p-3">Item Name</th>
                            <th className="p-3">Movement</th>
                            <th className="p-3">Quantity</th>
                            <th className="p-3">Previous</th>
                            <th className="p-3">New</th>
                            <th className="p-3">Performed By</th>
                        </tr>
                    </thead>

                    <tbody>
                        {data.movements.map((movement, index) => (
                            <tr key={index} className="border-t hover:bg-gray-50">
                            <td className="p-3">{movement.itemCode}</td>
                            <td className="p-3">{movement.itemName}</td>
                            <td className="p-3">{movement.movementType}</td>
                            <td className="p-3">{movement.quantity}</td>
                            <td className="p-3">{movement.previousQuantity}</td>
                            <td className="p-3">{movement.newQuantity}</td>
                            <td className="p-3">{movement.performedBy}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                </div>
            </>
        )}

        {reportType === "Financial Summary" && (
            <>
                <h3 className="text-lg font-semibold mb-4">
                  Financial Summary
                </h3>

                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">

                <div className="border rounded-lg p-4">
                    <p className="text-sm text-gray-500">Total Revenue</p>
                    <p className="text-xl font-bold text-emerald-600">
                    RWF {data.summary?.totalRevenue}
                    </p>
                </div>

                <div className="border rounded-lg p-4">
                    <p className="text-sm text-gray-500">Total Paid</p>
                    <p className="text-xl font-bold text-emerald-600">
                    RWF {data.summary?.totalPaid}
                    </p>
                </div>

                <div className="border rounded-lg p-4">
                    <p className="text-sm text-gray-500">Outstanding Balance</p>
                    <p className="text-xl font-bold text-red-600">
                    RWF {data.summary?.outstandingBalance}
                    </p>
                </div>

                <div className="border rounded-lg p-4">
                    <p className="text-sm text-gray-500">Inventory Value</p>
                    <p className="text-xl font-bold text-blue-600">
                    RWF {data.summary?.inventoryValue}
                    </p>
                </div>

                </div>
            </>
        )}

    </div>
  );
};

export default ReportViewer;